### ISSUE TITLE
Exit program memory leak

### ISSUE THREAD

**Issue by lobtao** [salvadordf/OldCEF4Delphi#3]
When set up
ReportMemoryLeaksOnShutdown := True;

---------------------------
Unexpected Memory Leak
---------------------------
An unexpected memory leak has occurred. The unexpected small block leaks are:

13 - 20 bytes: xxxx$ActRec x 1

**Comment by salvadordf** [comment]
It's the same issue that I already fixed in CEF4Delphi : 
https://github.com/salvadordf/CEF4Delphi/issues/89

It's fixed by moving the GlobalCEFApp creation and initialization outside the DPR file. I'll apply the fix to the demos as soon as I can.

**Comment by lobtao** [comment]
**1. set**

ReportMemoryLeaksOnShutdown := True;

**2. and** 

GlobalCEFApp.OnWebKitInitialized := GlobalCEFApp_OnWebKitInitializedEvent;

procedure GlobalCEFApp_OnWebKitInitializedEvent;
begin
  //empty
end;

**3.**
---------------------------
Unexpected Memory Leak
---------------------------
An unexpected memory leak has occurred. The unexpected small block leaks are:

13 - 20 bytes: niu_new$ActRec x 1

**Comment by salvadordf** [comment]
To avoid that leak you only have to assign all the GlobalCEFApp events in a PAS file.

The latest _JSExtensionWithObjectParameter_, _JSExtensionWithFunction_ and _JSSimpleExtension_ demos use a function called **CreateGlobalCEFApp** to create GlobalCEFApp and assign all the properties and events. CreateGlobalCEFApp is defined in the main PAS file. 

Please, download the latest OldCEF4Delphi and try those demos with ReportMemoryLeaksOnShutdown := True;

**Comment by lobtao** [comment]
good，CreateGlobalCEFApp  avoid that leak , why? the same code.

**Comment by salvadordf** [comment]
It's explained in detail here : 
https://stackoverflow.com/questions/9282103/anonymous-method-in-project-leaks-memory

Apparently, those events are never cleaned up from memory because the DPR never goes out of scope. The solution is moving that code to a PAS file that will always go out of scope.
