### ISSUE TITLE
compiledemos  on D2010

### ISSUE THREAD

**Issue by lobtao** [salvadordf/OldCEF4Delphi#4]
ResponseFilterBrowser    compile fail
SchemeRegistrationBrowser compile  success, but append error at run

**Comment by salvadordf** [comment]
I don't have Delphi 2010. Please, provide all the details you can about those errors. 
Thanks!

**Comment by salvadordf** [comment]
I have uploaded a new version of the ResponseFilterBrowser. I disabled a function that uses some TEncoding types that are not available in D2010.

 If you can fix GetResponseEncoding for Delphi 2010 send me the code or create a pull request.

Please, download OldCEF4Delphi again and let me know if you have more compilation problems. All the details you can provide are welcome.
