### ISSUE TITLE
FrameworkDirPath missing!

### ISSUE THREAD

**Issue by mylinc** [salvadordf/OldCEF4Delphi#5]
FrameworkDirPath, Is it missing?

**Comment by salvadordf** [comment]
See this issue : 
https://github.com/salvadordf/OldCEF4Delphi/issues/1

OldCEF4Delphi uses CEF 3.2623.1401.gb90a3be which was released on **May 11th, 2016** in this commit : 
https://bitbucket.org/chromiumembedded/cef/commits/b90a3be1860b0647e8a62c218ff7c054390365b1?at=2623
and the framework path setting was added much later on **January 27th, 2017** in this CEF3 commit : 
https://bitbucket.org/chromiumembedded/cef/commits/dda50912edce6919f1adbc86542e322656246111

CEF 3.2623.1401.gb90a3be was the last CEF version with Windows XP support. If you really need the FrameworkDirPath setting you would have to use CEF4Delphi : 
https://github.com/salvadordf/CEF4Delphi
