### ISSUE TITLE
Slow MS Excel startup while a web browser is running

### ISSUE THREAD

**Issue by z5104242** [salvadordf/OldCEF4Delphi#6]
If there is a TChromium running and you try to open a xlsx file from the explorer, Excel will take up to 40 seconds to start.

When you close the TChromium browser, Excel will start almost instantly.

Tested with :

Delphi 10 Seattle Subscription Update 1 and Delphi 10.2 Update 3

Microsoft Office Standard 2013 and Microsoft Office Standard 2016

Windows7 SP1

**Comment by salvadordf** [comment]
This issue was fixed at the same time than this one : https://github.com/salvadordf/CEF4Delphi/issues/139
Please, try the latest OldCEF4delphi version.
