### ISSUE TITLE
When using flash plug-ins, there will be a black screen flashing over

### ISSUE THREAD

**Issue by lobtao** [salvadordf/OldCEF4Delphi#7]
When using flash plug-ins, there will be a black screen flashing over

**Comment by salvadordf** [comment]
Please, provide more details to reproduce that issue. 

I just tested the MiniBrowser demo with the latest flash plugin installed in Windows and I could load and play several flash games.

Are you using the flash plugin installed in Windows? 
Are you using GlobalCEFApp.CustomFlashPath to load the plugin manually?
Are you using the "--ppapi-flash-path" and "--ppapi-flash-version" switches?

**Comment by lobtao** [comment]
It's already set up. Adding a cmd.exe to the current directory solves this problem.
`SetEnvironmentVariable('ComSpec', pchar(GetCurrentDir+'/cmd.exe'));`

**Comment by salvadordf** [comment]
Thanks for the information to solve this issue!
