### ISSUE TITLE
When you open DevTools, Chromium 1 KeyEvent cannot capture keyboard messages. I want to turn DevTools on and off via F12.

### ISSUE THREAD

**Issue by lobtao** [salvadordf/OldCEF4Delphi#8]
When you open DevTools, Chromium 1 KeyEvent cannot capture keyboard messages. I want to turn DevTools on and off via F12.

**Comment by salvadordf** [comment]
The MiniBrowser demo has the code to show and hide the DevTools with F12.
You need to use the TChromium.OnPreKeyEvent and TChromium.OnKeyEvent events to capture the key press and then send a message to the main form to show or hide the DevTools.
That demo also has a context menu option to show the DevTools and it uses the last mouse coordinates in a parameter to inspect the HTML element under the mouse.

**Comment by lobtao** [comment]
When DevTools is displayed, Chromium 1 loses focus. Press F12 again, and the DevTools window will not be closed. You need to click to activate Chromium 1 to trigger keyboard events.

**Comment by salvadordf** [comment]
Thanks! I'll take a look as soon as I can. 
Reopening this issue...

**Comment by salvadordf** [comment]
TChromium now uses the same event for the keyboard events coming from the browser and the DevTools. The MiniBrowser also sets the focus to the browser when it hides the DevTools and F12 works correctly.
