### ISSUE TITLE
Missing GlobalCEFApp.FrameworkDirPath

### ISSUE THREAD

**Issue by 156704883** [salvadordf/OldCEF4Delphi#9]
I have tried  to move all the binaries to another directory using OldCEF4Delphi ; 
sure enough it works！
so can use  FrameworkDirPath like cef4Delphi , change uCEFApplication.pas  and uCEFChromiumEvents

**Comment by salvadordf** [comment]
I'm glad that it worked but I'm afraid I can't add a FrameworkDirPath property. 

Please, read this to know  why : 
https://github.com/salvadordf/OldCEF4Delphi/issues/5
